### GET /
GET http://localhost:5000

### register user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "Peepee@sdfds.com",
    "password": "dsfsdfg"
}

### LOGIN USER POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "Peepee@sdfds.com",
    "password": "dsfsdfg"
}
